[:h3 "Tutorial"]

[:p "In this tutorial we will go through the following concepts..."]
[:ul
 [:li [:a {:href "/tutorial/step1"} "Getting Started"]]
 [:li [:a {:href "/tutorial/step2"} "Running Your 1st Test"]]
 [:li [:a {:href "/tutorial/step3"} "Understanding the Basics"]]
 [:li [:a {:href "/tutorial/step4"} "Splitting Test Code From Production Code"]]
 [:li [:a {:href "/tutorial/step4#ch5"} "Running Multiple Test Files"]]
 [:li [:a {:href "/tutorial/step5"} "Stubbing Standard Input and Output"]]
 [:li [:a {:href "/tutorial/step5#ch7"} "Run Tests Automatically"]]
 [:li [:a {:href "/tutorial/step6"} "Decoupling Tests"]]
 [:li [:a {:href "/tutorial/step6#ch9"} "Testing for Exceptions"]]
 [:li [:a {:href "/tutorial/step7"} "Testing Long Decimal Values with Simple Formatting"]]
]