[:h3 [:a {:name "ch3"} "Understanding the Basics"]]
[:p "Let's add some more code to understand how Speclj works. Let's type the code from <a href=\"#f5\">Figure 5</a> into our core_spec.clj file to get a deeper understanding of how Speclj components work."]

[:h5 [:a {:name "f5"} "Figure 5"]]
[:p "<pre class=\"textmate-source twilight\"><span class=\"source source_clojure\"><span class=\"meta meta_function meta_function_namespace meta_function_namespace_clojure\">(<span class=\"support support_function support_function_namespace support_function_namespace_clojure\">ns</span> <span class=\"entity entity_name entity_name_namespace entity_name_namespace_clojure\"><span class=\"source source_symbol source_symbol_clojure\">change_counter</span><span class=\"keyword keyword_operator keyword_operator_classpath keyword_operator_classpath_clojure\">.</span><span class=\"source source_symbol source_symbol_clojure\">core-spec</span></span>
  (<span class=\"support support_other support_other_keyword support_other_keyword_namespace support_other_keyword_namespace_clojure\">:use</span> [<span class=\"source source_symbol source_symbol_clojure\">speclj</span><span class=\"keyword keyword_operator keyword_operator_classpath keyword_operator_classpath_clojure\">.</span><span class=\"source source_symbol source_symbol_clojure\">core</span>]))</span>

<span class=\"meta meta_function meta_function_clojure\">(<span class=\"storage storage_type storage_type_function storage_type_function_type storage_type_function_type_clojure\">defn</span> <span class=\"entity entity_name entity_name_function entity_name_function_clojure\"><span class=\"source source_symbol source_symbol_clojure\">equals-5<span class=\"keyword keyword_other keyword_other_mark keyword_other_mark_clojure\">?</span></span></span> <span class=\"meta meta_function meta_function_body meta_function_body_clojure\"><span class=\"meta meta_function meta_function_parameters meta_function_parameters_vector meta_function_parameters_vector_clojure\"><span class=\"punctuation punctuation_definition punctuation_definition_vector punctuation_definition_vector_begin punctuation_definition_vector_begin_clojure\">[</span><span class=\"variable variable_parameter variable_parameter_clojure\"><span class=\"source source_symbol source_symbol_clojure\">n</span></span><span class=\"punctuation punctuation_definition punctuation_definition_vector punctuation_definition_vector_end punctuation_definition_vector_end_clojure\">]</span></span><span class=\"meta meta_function meta_function_body meta_function_body_code meta_function_body_code_clojure\">
  <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"keyword keyword_operator keyword_operator_clojure\">=</span> <span class=\"constant constant_numeric constant_numeric_float constant_numeric_float_clojure\">5</span> <span class=\"source source_symbol source_symbol_clojure\">n</span>)</span></span></span>)</span>

<span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">describe</span> <span class=\"string string_quoted string_quoted_double string_quoted_double_clojure\"><span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_clojure\">\"</span>Understanding Speclj Components<span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_clojure\">\"</span></span>
  <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">before-all</span>
    <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"storage storage_clojure\">println</span> <span class=\"string string_quoted string_quoted_double string_quoted_double_clojure\"><span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_clojure\">\"</span>Start testing<span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_clojure\">\"</span></span>)</span>)</span>
  
  <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">after-all</span>
    <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"storage storage_clojure\">println</span> <span class=\"string string_quoted string_quoted_double string_quoted_double_clojure\"><span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_clojure\">\"</span>Finished testing<span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_clojure\">\"</span></span>)</span>)</span>
    
  <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">before</span>
    <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"storage storage_clojure\">println</span> <span class=\"string string_quoted string_quoted_double string_quoted_double_clojure\"><span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_clojure\">\"</span>Before each test<span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_clojure\">\"</span></span>)</span>)</span>
    
  <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">after</span>
    <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"storage storage_clojure\">println</span> <span class=\"string string_quoted string_quoted_double string_quoted_double_clojure\"><span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_clojure\">\"</span>After each test<span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_clojure\">\"</span></span>)</span>)</span>

  <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">it</span> <span class=\"string string_quoted string_quoted_double string_quoted_double_clojure\"><span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_clojure\">\"</span>4 plus 1 equals 5<span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_clojure\">\"</span></span>
    <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"storage storage_clojure\">println</span> <span class=\"string string_quoted string_quoted_double string_quoted_double_clojure\"><span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_clojure\">\"</span>During 1st Test<span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_clojure\">\"</span></span>)</span>
    <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">should</span> <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">equals-5<span class=\"keyword keyword_other keyword_other_mark keyword_other_mark_clojure\">?</span></span> <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"keyword keyword_operator keyword_operator_clojure\">+</span> <span class=\"constant constant_numeric constant_numeric_float constant_numeric_float_clojure\">4</span> <span class=\"constant constant_numeric constant_numeric_float constant_numeric_float_clojure\">1</span>)</span>)</span>)</span>)</span>
    
  <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">it</span> <span class=\"string string_quoted string_quoted_double string_quoted_double_clojure\"><span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_clojure\">\"</span>4 plus 2 doesn't equal 5<span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_clojure\">\"</span></span>
    <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"storage storage_clojure\">println</span> <span class=\"string string_quoted string_quoted_double string_quoted_double_clojure\"><span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_clojure\">\"</span>During 2nd Test<span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_clojure\">\"</span></span>)</span>
    <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">should-not</span> <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">equals-5<span class=\"keyword keyword_other keyword_other_mark keyword_other_mark_clojure\">?</span></span> <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"keyword keyword_operator keyword_operator_clojure\">+</span> <span class=\"constant constant_numeric constant_numeric_float constant_numeric_float_clojure\">4</span> <span class=\"constant constant_numeric constant_numeric_float constant_numeric_float_clojure\">2</span>)</span>)</span>)</span>)</span>
  
  <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">it</span> <span class=\"string string_quoted string_quoted_double string_quoted_double_clojure\"><span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_clojure\">\"</span>4 plus 2 equals 6<span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_clojure\">\"</span></span>
    <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"storage storage_clojure\">println</span> <span class=\"string string_quoted string_quoted_double string_quoted_double_clojure\"><span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_clojure\">\"</span>During 3rd Test<span class=\"punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_clojure\">\"</span></span>)</span>
    <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">should<span class=\"keyword keyword_other keyword_other_mark keyword_other_mark_clojure\">=</span></span> <span class=\"constant constant_numeric constant_numeric_float constant_numeric_float_clojure\">6</span> <span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"keyword keyword_operator keyword_operator_clojure\">+</span> <span class=\"constant constant_numeric constant_numeric_float constant_numeric_float_clojure\">4</span> <span class=\"constant constant_numeric constant_numeric_float constant_numeric_float_clojure\">2</span>)</span>)</span>)</span>
)</span>

<span class=\"meta meta_sexpr meta_sexpr_clojure\">(<span class=\"source source_symbol source_symbol_clojure\">run-specs</span>)</span></span></pre>"]

[:p "If you run the tests, it becomes obvious what the before-all, after-all, before, and after components do. In the case of <a href=\"#f5\">Figure 5</a> they are being used trivially to display their functionality, however they are very useful when a lot of your tests require the same setup or teardown code."]

[:p "Another thing to notice from <a href=\"#f5\">Figure 5</a> is the difference between the should, should-not, and should= components. In the case of should and should-not, they get passed a value of true or false and pass or fail accordingly. However the should= component takes two arguments. The 1st argument represents the expected result of the 2nd argument. The 2nd argument is the value actually being tested."]
[:span {:id "lesson_nav"} [:a {:href "/tutorial/step2"} "<-- Running 1st Test"] "&nbsp;&nbsp;|&nbsp;&nbsp;" [:a {:href "/tutorial/step4"} "Separating Test Code -->"]]