[:div {:id "sidebar"}
  [:h3 "Speclj Components"]
  [:a {:href "/docs/describe"} "describe"] [:br]
  [:a {:href "/docs/it"} "it"] [:br]
  [:a {:href "/docs/should"} "should"] [:br]
  [:a {:href "/docs/should-not"} "should-not"] [:br]
  [:a {:href "/docs/should-e"} "should="] [:br]
  [:a {:href "/docs/should-not-e"} "should-not="] [:br]
  [:a {:href "/docs/should-fail"} "should-fail"] [:br]
  [:a {:href "/docs/should-throw"} "should-throw"] [:br]
  [:a {:href "/docs/should-not-throw"} "should-not-throw"] [:br]
  [:a {:href "/docs/before"} "before"] [:br]
  [:a {:href "/docs/before-all"} "before-all"] [:br]
  [:a {:href "/docs/after"} "after"] [:br]
  [:a {:href "/docs/after-all"} "after-all"] [:br]
  [:a {:href "/docs/with"} "with"] [:br]
  [:a {:href "/docs/around"} "around"]
]