[:ul
 [:li [:a {:href "/tutorial/step1"} "Getting Started"]]
 [:li [:a {:href "/tutorial/step2"} "Running 1st Test"]]
 [:li [:a {:href "/tutorial/step3"} "The Basics"]]
 [:li [:a {:href "/tutorial/step4"} "Separating Test Code"]]
 [:li [:a {:href "/tutorial/step4#ch5"} "Multiple Test Files"]]
 [:li [:a {:href "/tutorial/step5"} "Testing Input and Output"]]
 [:li [:a {:href "/tutorial/step5#ch7"} "Automated Testing"]]
 [:li [:a {:href "/tutorial/step6"} "Decoupling Tests"]]
 [:li [:a {:href "/tutorial/step6#ch9"} "Exception Testing"]]
 [:li [:a {:href "/tutorial/step7"} "Reference-able Symbols"]]
]